import { PoolClient } from 'pg'
import { v4 as uuidv4 } from 'uuid'

export const run = async (client: PoolClient): Promise<void> => {
  await client.query(`
    CREATE TABLE IF NOT EXISTS users (
      id         int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name text        NOT NULL,
      last_name  text        NOT NULL,
      email      text        NOT NULL UNIQUE,
      password   text        NOT NULL,
      token      text        NOT NULL,
      created    timestamptz NOT NULL DEFAULT now(),
      last_login timestamptz NOT NULL DEFAULT now(),
      studio     boolean     NOT NULL DEFAULT FALSE,
      admin      boolean     NOT NULL DEFAULT FALSE
    )
  `)

  await client.query('CREATE INDEX ON users (token)')

  const uuid: string = uuidv4().replace(/-/g, '')

  await client.query(`
    INSERT INTO users (first_name, last_name, email, password, token, studio, admin)
    VALUES ('Bridget', 'Johansen', 'email@bridgetjohansen.com', '${uuid}', '${uuid}', TRUE, TRUE),
           ('Rob', 'Johansen', 'admin@bridgetjohansen.com', '${uuid}', '${uuid}', TRUE, TRUE)
  `)
}
