import { PoolClient } from 'pg'

export const run = async (client: PoolClient): Promise<void> => {
  await client.query(`
    CREATE TABLE IF NOT EXISTS migrations (
      id     int         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name   text        NOT NULL,
      run_at timestamptz NOT NULL DEFAULT now()
    )
  `)
}
